#+title: This is new

* From scratch

Welcome to my first website. That is, I've had websites on Blogger or Wordpress. But this is the first one that I made from scratch.

/From scratch?/ you say. /Why ever for?/ you say.

A website has always been a sign of independence for me, like an actual signboard painted by a professional artisan. It's important to capture the look and feel of the person in the website and the look-and-feel selection in Blogger, Tumblr and Wordpress is limited. It's still a lot, but you'd have to jump through hoops to get it just right.

What if we could get it just right without having to jump through all those hoops? This website isn't "just right" quite yet, but right off the bat it's closer than any of those other websites will ever be. So grab a chair, kick off your shoes.

Make yourself at home. Changing a thing to check committing to remote repository.

** Teaching

I use task-based language teaching to support learners. Go [[./teaching.org][here]] for more info.

** Proofreading

I check for editorial style and more!

** Poetry

I write poetry

#+begin_verse
Let it breathe
the wound
yada yada
#+end_verse
